name: ${COMPOSE_PROJECT_NAME:-ifq683-a1}

services:
  nginx:
    image: nginx:1.27-alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ${NGINX_CONFIG_PATH:-./.docker/nginx/default.conf}:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
